PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE FORCELOGOUT_MONITOR (ID INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, REQUEST_ID VARCHAR UNIQUE, LOGIN_REQ VARCHAR, FORCE_LOGOUT_REQ VARCHAR, LOGIN_ANS VARCHAR, FORCE_LOGOUT_ANS VARCHAR);
CREATE TABLE LOGIN_MONITOR (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, REQUEST_ID VARCHAR UNIQUE, LOGIN_REQ VARCHAR, LOGIN_ANS VARCHAR, USER_INFO VARCHAR, OC_POSITION);
CREATE TABLE LOGOUT_MONITOR (ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, REQUEST_ID VARCHAR UNIQUE NOT NULL, LOGOUT_REQ VARCHAR, LOGOUT_ANS VARCHAR, SYN_POSITION_REQ VARCHAR, POSITION_RES VARCHAR);
CREATE TABLE TAG_ERROR (ID INTEGER PRIMARY KEY, RESPONSE_QUEUE VARCHAR, TAG INTEGER, MESSAGE_TYPE VARCHAR, BODY VARCHAR);



CREATE INDEX reqid_logout ON LOGOUT_MONITOR (REQUEST_ID);
CREATE UNIQUE INDEX req_login ON LOGIN_MONITOR (REQUEST_ID);
CREATE INDEX req_fl ON FORCELOGOUT_MONITOR (REQUEST_ID);


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;

