//
// Created by alex on 2/27/17.
//

#ifndef TRADINGENGINE_TRADINGERRNO_H
#define TRADINGENGINE_TRADINGERRNO_H

#ifndef UNIVERSAL_TRADING
#define UNIVERSAL_TRADING                                        0x01010000

#define DEFINED_TRADING_ERRNO(errno)                             ((UNIVERSAL_TRADING) | (errno))

#define UNIVERSAL_TRADING_SUCCESS                                0x0
#define UNIVERSAL_TRADING_REPEAT_INIT_ERR                        DEFINED_TRADING_ERRNO(1)
#define UNIVERSAL_TRADING_CONFIG_PARAMETER_ERR                   DEFINED_TRADING_ERRNO(2)
#define UNIVERSAL_TRADING_MESSAGE_DATA_ERR                       DEFINED_TRADING_ERRNO(3)
#define UNIVERSAL_TRADING_NO_IMPLEMENT_ERR                       DEFINED_TRADING_ERRNO(4)
#define UNIVERSAL_TRADING_SEND_ORDER_MSG_ERR                     DEFINED_TRADING_ERRNO(5)
#define UNIVERSAL_TRADING_ORDER_QUEUE_INIT_ERR                   DEFINED_TRADING_ERRNO(6)
#define UNIVERSAL_TRADING_ALLOC_QUEUE_ERR                        DEFINED_TRADING_ERRNO(7)
#define UNIVERSAL_TRADING_ORDER_ANS_QUEUE_INIT_ERR               DEFINED_TRADING_ERRNO(8)
#define UNIVERSAL_TRADING_VALIDATE_MSG_ERR                       DEFINED_TRADING_ERRNO(9)
#define UNIVERSAL_TRADING_VALIDATE_REJECT_ERR                    DEFINED_TRADING_ERRNO(10)
#define UNIVERSAL_TRADING_SYMBOL_ERR                             DEFINED_TRADING_ERRNO(11)
#define UNIVERSAL_TRADING_MARKET_DATA_INVALID_ERR                DEFINED_TRADING_ERRNO(12)
#define UNIVERSAL_TRADING_ACKNOWLEDGE_MSG_ERR                    DEFINED_TRADING_ERRNO(13)
#define UNIVERSAL_TRADING_ORDER_ANS_REQID_ERR                    DEFINED_TRADING_ERRNO(14)
#define UNIVERSAL_TRADING_ORDER_ANS_MSG_ERR                      DEFINED_TRADING_ERRNO(15)
#define UNIVERSAL_TRADING_ALLOC_DATABUFF_ERR                     DEFINED_TRADING_ERRNO(16)
#define UNIVERSAL_TRADING_NO_INIT_ERR                            DEFINED_TRADING_ERRNO(17)
#define UNIVERSAL_TRADING_MONITOR_MSG_ERR                        DEFINED_TRADING_ERRNO(18)
#define UNIVERSAL_TRADING_READ_SQLITE_ERR                        DEFINED_TRADING_ERRNO(19)

#endif

#endif //TRADINGENGINE_TRADINGERRNO_H
