-- spread group
CREATE TABLE GROUP_1 (ID INTEGER PRIMARY KEY AUTOINCREMENT, SPREAD INTEGER, SYMBOLS VARCHAR, CREATE_TIME DATETIME);

-- raw data

CREATE TABLE RAW_AUD_CAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUD_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUD_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUD_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUD_NZD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUD_SGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUD_USD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CAD_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CAD_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CAD_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_CAD_SGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CHF_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CHF_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CHF_ZAR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_AUD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_CAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_CZK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_DKK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_GBP (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_EUR_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_HUF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_NOK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_NZD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_PLN (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_SEK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_SGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_TRY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EUR_USD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_EUR_ZAR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_AUD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_CAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_NZD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_PLN (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_SGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBP_USD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_GBP_ZAR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_HKD_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZD_CAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZD_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZD_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZD_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZD_SGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZD_USD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_SGD_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_SGD_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_SGD_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_TRY_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_CAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_CHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_CNH (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_CZK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_DKK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_HKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_HUF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_INR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_USD_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_MXN (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_NOK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_PLN (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_SAR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_SEK (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_SGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_THB (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_TRY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USD_ZAR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_ZAR_JPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, TIME VARCHAR, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_FINCOIN_USD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, TIME VARCHAR, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_SymbolBUTT (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, TIME VARCHAR, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

