-- raw data

CREATE TABLE RAW_AUDCAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUDSGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CADSGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURCAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBPJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZDJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_SGDJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USDJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_ZARJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUDCHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_AUDUSD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURCHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBPAUD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBPNZD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_TRYJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USDSGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CADCHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CHFJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURSGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_GBPCAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZDCAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZDUSD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USDCAD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USDHKD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUDJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURTRY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBPCHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBPSGD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_NZDCHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_USDCHF (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USDTRY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_AUDNZD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_CADJPY (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURAUD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURGBP (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURNZD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_EURUSD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_GBPUSD (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);
CREATE TABLE RAW_USDCNH (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

CREATE TABLE RAW_USDINR (ID INTEGER PRIMARY KEY AUTOINCREMENT, STATUS INT, TIME VARCHAR, BID DOUBLE, ASK DOUBLE, TIMESTAMP INTEGER, TIME_FORMAT VARCHAR);

