//
// Created by alex on 12/16/16.
//

#ifndef MARKET_ERRNO_H
#define MARKET_ERRNO_H


#define UNIVERSAL_MARKET                                        0x02010000

#define DEFINED_MARKET_ERRNO(errno)                             ((UNIVERSAL_MARKET) | (errno))

#define UNIVERSAL_MARKET_SUCCESS                                0x0
#define UNIVERSAL_MARKET_UNKNOWN                                DEFINED_MARKET_ERRNO(1)
#define UNIVERSAL_MARKET_PARAMETER_ERR                          DEFINED_MARKET_ERRNO(2)
#define UNIVERSAL_MARKET_NULL_PTR_ERR                           DEFINED_MARKET_ERRNO(3)
#define UNIVERSAL_MARKET_INIT_FAILED_ERR                        DEFINED_MARKET_ERRNO(4)
#define UNIVERSAL_MARKET_CONFIG_PARAMETER_ERR                   DEFINED_MARKET_ERRNO(5)
#define UNIVERSAL_MARKET_RECEIVED_EMPTY_DATA_ERR                DEFINED_MARKET_ERRNO(6)
#define UNIVERSAL_MARKET_NO_ENOUGH_DATA_BUFFER_ERR              DEFINED_MARKET_ERRNO(7)
#define UNIVERSAL_MARKET_GET_MARKETDATA_ERR                     DEFINED_MARKET_ERRNO(8)
#define UNIVERSAL_MARKET_ALLOC_DATA_BUFFER_ERR                  DEFINED_MARKET_ERRNO(9)
#define UNIVERSAL_MARKET_MARKETDATA_FIELD_ERR                   DEFINED_MARKET_ERRNO(10)
#define UNIVERSAL_MARKET_NO_SUPPORT_SYMBOL_ERR                  DEFINED_MARKET_ERRNO(11)
#define UNIVERSAL_MARKET_NO_IMPLEMENT_ERR                       DEFINED_MARKET_ERRNO(12)
#define UNIVERSAL_MARKET_MESSAGE_DATA_ERR                       DEFINED_MARKET_ERRNO(13)
#define UNIVERSAL_MARKET_REPEAT_INIT_ERR                        DEFINED_MARKET_ERRNO(14)


#endif //MARKET_ERRNO_H
